import React from 'react';
import { useLanguage } from '../context/LanguageContext';

const Terms: React.FC = () => {
    const { t } = useLanguage();

    return (
        <section className="section-padding" style={{ minHeight: '80vh' }}>
            <div className="container" style={{ maxWidth: '720px' }}>
                <h2 style={{ marginBottom: '32px' }}>{t('terms_title') || 'Terms of Service'}</h2>

                <div style={{ opacity: 0.85, lineHeight: 1.8, fontSize: '1.05rem' }}>
                    <p style={{ marginBottom: '20px', fontStyle: 'italic', opacity: 0.7 }}>
                        {t('terms_last_updated') || 'Last updated: April 2026'}
                    </p>

                    <h3 style={{ marginTop: '24px', marginBottom: '12px', color: 'var(--accent-gold)' }}>
                        1. {t('terms_scope_title') || 'Scope & Subject'}
                    </h3>
                    <p>{t('terms_scope_text') || 'These Terms of Service ("Terms") govern your use of the ReadyLegacy platform ("Service"), operated by ReadyLegacy, c/o Dr. Inna Praxmarer, Switzerland. By creating an account or using the Service, you agree to these Terms.'}</p>

                    <h3 style={{ marginTop: '24px', marginBottom: '12px', color: 'var(--accent-gold)' }}>
                        2. {t('terms_service_title') || 'Service Description'}
                    </h3>
                    <p>{t('terms_service_text') || 'ReadyLegacy is a digital platform for organizing estate planning, legacy preservation, and bereavement support. The Service is an organizational tool and does NOT provide legal, financial, or medical advice. All tools and templates are intended as organizational aids and do not replace professional consultation.'}</p>

                    <h3 style={{ marginTop: '24px', marginBottom: '12px', color: 'var(--accent-gold)' }}>
                        3. {t('terms_account_title') || 'Account & Registration'}
                    </h3>
                    <p>{t('terms_account_text') || 'To use cloud features, you must create an account with a valid email address. You must be at least 18 years old. You are responsible for maintaining the confidentiality of your login credentials and for all activities under your account.'}</p>

                    <h3 style={{ marginTop: '24px', marginBottom: '12px', color: 'var(--accent-gold)' }}>
                        4. {t('terms_data_title') || 'Data Storage & Security'}
                    </h3>
                    <p>{t('terms_data_text') || 'Your data is stored locally in your browser and, when logged in, synchronized to our cloud database (hosted in the EU). Data is transmitted over encrypted connections (HTTPS/TLS). You are responsible for the accuracy and completeness of the data you enter. We recommend regularly reviewing your stored information.'}</p>

                    <h3 style={{ marginTop: '24px', marginBottom: '12px', color: 'var(--accent-gold)' }}>
                        5. {t('terms_liability_title') || 'Limitation of Liability'}
                    </h3>
                    <p>{t('terms_liability_text') || 'ReadyLegacy is provided "as is" without warranties of any kind. We are not liable for: (a) the legal validity of any documents created using our tools; (b) decisions made based on information stored on our platform; (c) data loss beyond our reasonable control; (d) any indirect, incidental, or consequential damages. Our liability is limited to intent and gross negligence under Swiss law (OR Art. 100).'}</p>

                    <h3 style={{ marginTop: '24px', marginBottom: '12px', color: 'var(--accent-gold)' }}>
                        6. {t('terms_death_title') || 'Access After Death'}
                    </h3>
                    <p>{t('terms_death_text') || 'In the event of a user\'s death, authorized persons (registered beneficiaries or legal heirs) may request access to the deceased user\'s data by contacting us at info@readylegacy.ch with a death certificate and proof of identity. ReadyLegacy reserves the right to verify the legitimacy of any such request. We do not act as an executor or legal representative.'}</p>

                    <h3 style={{ marginTop: '24px', marginBottom: '12px', color: 'var(--accent-gold)' }}>
                        7. {t('terms_no_legal_title') || 'No Legal Advice'}
                    </h3>
                    <p>{t('terms_no_legal_text') || 'ReadyLegacy does not provide legal, financial, tax, or medical advice. Content generated by our tools and AI assistant is for informational and organizational purposes only. Documents created on our platform (including wills, directives, and powers of attorney) have no legal validity unless separately formalized according to applicable law. Always consult a qualified professional.'}</p>

                    <h3 style={{ marginTop: '24px', marginBottom: '12px', color: 'var(--accent-gold)' }}>
                        8. {t('terms_termination_title') || 'Termination & Deletion'}
                    </h3>
                    <p>{t('terms_termination_text') || 'You may delete your account at any time via your Profile settings. Upon deletion, all your data is permanently removed from our database. We may terminate accounts that violate these Terms. For paid plans, cancellation takes effect at the end of the current billing period.'}</p>

                    <h3 style={{ marginTop: '24px', marginBottom: '12px', color: 'var(--accent-gold)' }}>
                        9. {t('terms_ip_title') || 'Intellectual Property'}
                    </h3>
                    <p>{t('terms_ip_text') || 'The ReadyLegacy platform, including its design, code, and content, is protected by copyright and intellectual property laws. You retain ownership of all data you enter. By using the Service, you grant us a limited license to store and process your data solely for providing the Service.'}</p>

                    <h3 style={{ marginTop: '24px', marginBottom: '12px', color: 'var(--accent-gold)' }}>
                        10. {t('terms_law_title') || 'Applicable Law & Jurisdiction'}
                    </h3>
                    <p>{t('terms_law_text') || 'These Terms are governed by Swiss law. The exclusive place of jurisdiction is Switzerland. For consumers in the EU, mandatory consumer protection provisions of their country of residence may apply.'}</p>

                    <h3 style={{ marginTop: '24px', marginBottom: '12px', color: 'var(--accent-gold)' }}>
                        11. {t('terms_changes_title') || 'Changes to Terms'}
                    </h3>
                    <p>{t('terms_changes_text') || 'We may update these Terms from time to time. Significant changes will be communicated via email or in-app notification. Continued use of the Service after changes constitutes acceptance of the updated Terms.'}</p>

                    <h3 style={{ marginTop: '24px', marginBottom: '12px', color: 'var(--accent-gold)' }}>
                        12. {t('privacy_contact_title') || 'Contact'}
                    </h3>
                    <p>
                        Email: <a href="mailto:info@readylegacy.ch" style={{ color: 'var(--accent-gold)' }}>info@readylegacy.ch</a><br />
                        Web: <a href="https://readylegacy.ch" style={{ color: 'var(--accent-gold)' }}>readylegacy.ch</a>
                    </p>
                </div>
            </div>
        </section>
    );
};

export default Terms;
